import base64
import fcntl
import html
import importlib
import json
import os
import re
import sys

# Import PySide6 first and neutralize its "__feature__" auto-detection hook
# *before* anything else is imported. That hook wraps every subsequent
# import to run inspect.getsource() on the freshly-loaded module, which
# crashes inside PyInstaller-frozen builds the moment it reaches pynput's
# import chain (AttributeError: '_SixMetaPathImporter' object has no
# attribute '_path'). This app never uses PySide6's __feature__ system
# (true_property / snake_case), so disabling the auto-detection is safe.
import PySide6.QtCore  # noqa: F401  (bootstraps shiboken's support machinery)
try:
    import shibokensupport.feature as _shiboken_feature
    _shiboken_feature._mod_uses_pyside = lambda mod: False
except ImportError:
    pass

# Quartz (part of pyobjc) is macOS-only and optional: without it, auto-paste
# is simply disabled rather than crashing the app.
try:
    import Quartz
except ImportError:
    Quartz = None

from pynput import keyboard
from PySide6.QtCore import (
    QBuffer,
    QByteArray,
    QIODevice,
    QMimeData,
    QObject,
    QPoint,
    QRectF,
    QSettings,
    QThread,
    QTimer,
    QUrl,
    Qt,
    Signal,
)
from PySide6.QtGui import QBrush, QColor, QCursor, QImage, QPainter, QPainterPath, QPen, QPixmap
from PySide6.QtNetwork import QNetworkAccessManager, QNetworkRequest
from PySide6.QtWidgets import (
    QAbstractItemView,
    QApplication,
    QButtonGroup,
    QCheckBox,
    QDialog,
    QDialogButtonBox,
    QFormLayout,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListWidget,
    QListWidgetItem,
    QPushButton,
    QSizePolicy,
    QVBoxLayout,
    QWidget,
)

# Where pinned clipboard items are persisted, so they survive a full app quit.
APP_SUPPORT_DIR = os.path.expanduser("~/Library/Application Support/Clippy")
PINNED_STORE_PATH = os.path.join(APP_SUPPORT_DIR, "pinned.json")

SETTINGS = QSettings("ClippyApp", "Clippy")
DEFAULT_HOTKEY = "<cmd>+<shift>+v"

# Pasteboard types apps use (by convention: https://nspasteboard.org) to mark
# a copy as private - password managers being the main example. Respecting
# them means Clippy simply never records that particular copy.
PRIVATE_MARKER_TYPES = (
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
)

# --- Lightweight content sniffing, used to choose a preview style ----------
HEX_COLOR_RE = re.compile(r"^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$")
RGB_COLOR_RE = re.compile(r"^rgba?\(\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}\s*(?:,\s*[\d.]+\s*)?\)$", re.IGNORECASE)
HSL_COLOR_RE = re.compile(r"^hsla?\(\s*\d{1,3}\s*,\s*\d{1,3}%\s*,\s*\d{1,3}%\s*(?:,\s*[\d.]+\s*)?\)$", re.IGNORECASE)
URL_RE = re.compile(r"^(https?://|www\.)\S+$", re.IGNORECASE)
TITLE_TAG_RE = re.compile(rb"<title[^>]*>(.*?)</title>", re.IGNORECASE | re.DOTALL)

CODE_HINTS = (
    "def ", "class ", "function", "=>", "import ", "#include", "console.log(",
    "public static", "SELECT ", "</", "{", "};", "print(", "return ",
)


def classify_text(text: str) -> str:
    """Very lightweight heuristic used only to pick a preview style - not exact."""
    stripped = text.strip()
    if HEX_COLOR_RE.match(stripped) or RGB_COLOR_RE.match(stripped) or HSL_COLOR_RE.match(stripped):
        return "color"
    if URL_RE.match(stripped) and " " not in stripped:
        return "url"
    if len(stripped) <= 4000 and (stripped.count("\n") >= 2 or any(hint in text for hint in CODE_HINTS)):
        return "code"
    return "text"


def simulate_cmd_v():
    """Synthesize a system-wide Cmd+V keystroke (macOS only, needs Accessibility access)."""
    if Quartz is None:
        return
    src = Quartz.CGEventSourceCreate(Quartz.kCGEventSourceStateHIDSystemState)
    key_down = Quartz.CGEventCreateKeyboardEvent(src, 9, True)   # 9 == 'V'
    Quartz.CGEventSetFlags(key_down, Quartz.kCGEventFlagMaskCommand)
    key_up = Quartz.CGEventCreateKeyboardEvent(src, 9, False)
    Quartz.CGEventSetFlags(key_up, Quartz.kCGEventFlagMaskCommand)
    Quartz.CGEventPost(Quartz.kCGHIDEventTap, key_down)
    Quartz.CGEventPost(Quartz.kCGHIDEventTap, key_up)


# Enforce single instance execution using a lock file
lock_file = "/tmp/Clippy.lock"
try:
    lock_file_fd = open(lock_file, "w")
    fcntl.lockf(lock_file_fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
except (IOError, OSError):
    sys.exit(0)

# Hide application icon from the macOS Dock (Agent Application mode)
if sys.platform == "darwin":
    try:
        appkit = importlib.import_module("AppKit")
        ns_app = getattr(appkit, "NSApplication")
        ns_policy = getattr(appkit, "NSApplicationActivationPolicyAccessory")
        app_native = ns_app.sharedApplication()
        app_native.setActivationPolicy_(ns_policy)
    except (ImportError, AttributeError):
        pass


class HotkeySignal(QObject):
    """Signal emitter for thread-safe UI interactions from pynput listener."""
    triggered = Signal()


class HotkeyListenerThread(QThread):
    """Background thread listening for the configured global shortcut."""

    def __init__(self, hk_signal, hotkey):
        super().__init__()
        self.signal = hk_signal
        self.hotkey = hotkey
        self.listener = None

    def run(self):
        try:
            hotkeys = {self.hotkey: self.on_triggered}
            with keyboard.GlobalHotKeys(hotkeys) as listener:
                self.listener = listener
                listener.join()
        except (KeyError, ValueError, RuntimeError) as e:
            print(f"[ERROR] pynput listener: {e}")

    def on_triggered(self):
        self.signal.triggered.emit()

    def stop(self):
        if self.listener:
            self.listener.stop()
        self.quit()
        self.wait()


class PinButton(QPushButton):
    """A small checkable button drawn as an outlined pin; fills white when pinned."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setCheckable(True)
        self.setFixedSize(22, 22)
        self.setCursor(Qt.CursorShape.PointingHandCursor)
        self.setStyleSheet("QPushButton { background: transparent; border: none; }")
        self.setToolTip("Pin")

    def enterEvent(self, event):
        self.update()
        super().enterEvent(event)

    def leaveEvent(self, event):
        self.update()
        super().leaveEvent(event)

    @staticmethod
    def _pin_path(rect: QRectF) -> QPainterPath:
        """Builds a simple thumbtack-style pin silhouette inside `rect`."""
        w, h = rect.width(), rect.height()
        x, y = rect.left(), rect.top()

        head_d = w * 0.62
        head_rect = QRectF(x + (w - head_d) / 2, y, head_d, head_d)

        path = QPainterPath()
        path.addEllipse(head_rect)

        needle = QPainterPath()
        needle.moveTo(x + w * 0.38, y + head_d * 0.85)
        needle.lineTo(x + w * 0.62, y + head_d * 0.85)
        needle.lineTo(x + w * 0.5, y + h)
        needle.closeSubpath()

        path.addPath(needle)
        return path

    def paintEvent(self, event):
        painter = QPainter(self)
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)

        rect = QRectF(self.rect().adjusted(3, 2, -3, -2))
        path = self._pin_path(rect)

        if self.isChecked():
            painter.setBrush(QBrush(QColor("#ffffff")))
            painter.setPen(QPen(QColor("#ffffff"), 1))
        else:
            color = QColor("#ffffff") if self.underMouse() else QColor("#999999")
            painter.setBrush(Qt.BrushStyle.NoBrush)
            painter.setPen(QPen(color, 1.4))

        painter.drawPath(path)


class DeleteButton(QPushButton):
    """Small 'x' button that removes a single history entry (pinned or not)."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setFixedSize(20, 20)
        self.setCursor(Qt.CursorShape.PointingHandCursor)
        self.setStyleSheet("QPushButton { background: transparent; border: none; }")
        self.setToolTip("Remove")

    def enterEvent(self, event):
        self.update()
        super().enterEvent(event)

    def leaveEvent(self, event):
        self.update()
        super().leaveEvent(event)

    def paintEvent(self, event):
        painter = QPainter(self)
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)
        rect = self.rect().adjusted(6, 6, -6, -6)
        color = QColor("#ff5555") if self.underMouse() else QColor("#777777")
        pen = QPen(color, 1.6)
        pen.setCapStyle(Qt.PenCapStyle.RoundCap)
        painter.setPen(pen)
        painter.drawLine(rect.topLeft(), rect.bottomRight())
        painter.drawLine(rect.topRight(), rect.bottomLeft())


class HistoryRowWidget(QWidget):
    """Row rendered inside the list: type-aware preview + pin/delete toggles.

    Clicking anywhere on the row except the two buttons pastes the item;
    the pin/delete buttons only fire their own signals.
    """

    MONOSPACE = "'SF Mono', Menlo, Consolas, monospace"
    ELIDE_WIDTH = 170

    activated = Signal()
    pin_toggled = Signal()
    delete_requested = Signal()

    def __init__(self, item, parent=None):
        super().__init__(parent)

        layout = QHBoxLayout(self)
        layout.setContentsMargins(4, 2, 4, 2)
        layout.setSpacing(6)

        self.icon_label = QLabel(self)
        self.icon_label.setFixedSize(28, 28)
        self.icon_label.setScaledContents(True)
        self.icon_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.text_label = QLabel(self)
        self.text_label.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)

        self._build_content(item)

        self.pin_btn = PinButton(self)
        self.pin_btn.setChecked(bool(item.get("pinned", False)))
        self.pin_btn.clicked.connect(self.pin_toggled.emit)

        self.delete_btn = DeleteButton(self)
        self.delete_btn.clicked.connect(self.delete_requested.emit)

        layout.addWidget(self.icon_label)
        layout.addWidget(self.text_label, 1)
        layout.addWidget(self.pin_btn)
        layout.addWidget(self.delete_btn)

    def _elide(self, text):
        fm = self.text_label.fontMetrics()
        return fm.elidedText(text, Qt.TextElideMode.ElideRight, self.ELIDE_WIDTH)

    def _build_content(self, item):
        """(Re)renders icon + text for the given item; safe to call again later
        once async data (e.g. a fetched favicon/title) becomes available."""
        if item["type"] == "image":
            image: QImage = item["data"]
            pixmap = QPixmap.fromImage(image).scaled(
                28, 28, Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation,
            )
            self.icon_label.show()
            self.icon_label.setText("")
            self.icon_label.setPixmap(pixmap)
            self.icon_label.setStyleSheet("background: transparent; border-radius: 4px;")
            self.text_label.setStyleSheet("color: #cccccc; font-size: 13px; background: transparent;")
            self.text_label.setText(self._elide(" [Image / Screenshot]"))
            return

        raw_text = " ".join(item["data"].split())
        kind = item.get("kind", "text")

        if kind == "color":
            color = QColor(raw_text.strip())
            if not color.isValid():
                color = QColor("#666666")
            self.icon_label.show()
            self.icon_label.setText("")
            self.icon_label.setPixmap(QPixmap())
            self.icon_label.setStyleSheet(
                f"background-color: {color.name()}; border-radius: 6px; border: 1px solid #444444;"
            )
            self.text_label.setStyleSheet(
                f"color: {color.name()}; font-size: 13px; font-family: {self.MONOSPACE}; background: transparent;"
            )
            self.text_label.setText(self._elide(raw_text))

        elif kind == "url":
            self.icon_label.show()
            favicon_b64 = item.get("link_favicon_b64")
            if favicon_b64:
                pixmap = QPixmap()
                pixmap.loadFromData(base64.b64decode(favicon_b64))
                self.icon_label.setText("")
                self.icon_label.setPixmap(
                    pixmap.scaled(20, 20, Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation)
                )
                self.icon_label.setStyleSheet("background: transparent;")
            else:
                self.icon_label.setPixmap(QPixmap())
                self.icon_label.setText("\U0001F517")  # link emoji as a placeholder
                self.icon_label.setStyleSheet("background: transparent; font-size: 15px;")
            self.text_label.setStyleSheet("color: #6ab0f3; font-size: 13px; background: transparent;")
            self.text_label.setText(self._elide(item.get("link_title") or raw_text))

        elif kind == "code":
            self.icon_label.show()
            self.icon_label.setPixmap(QPixmap())
            self.icon_label.setText("</>")
            self.icon_label.setStyleSheet("background: transparent; color: #888888; font-size: 10px;")
            self.text_label.setStyleSheet(
                f"color: #cccccc; font-size: 12px; font-family: {self.MONOSPACE}; background: transparent;"
            )
            self.text_label.setText(self._elide(raw_text))

        else:
            self.icon_label.hide()
            self.text_label.setStyleSheet("color: #cccccc; font-size: 13px; background: transparent;")
            self.text_label.setText(self._elide(raw_text))

    def mousePressEvent(self, event):
        # Clicks that land on a button are consumed by the button itself and
        # never reach here, so any press we do see is a "paste" click.
        if event.button() == Qt.MouseButton.LeftButton:
            self.activated.emit()
        super().mousePressEvent(event)


class HotkeyCaptureField(QLineEdit):
    """Read-only field: click it, then press a modifier+key combo to record it.

    Supports letters/digits/symbols with at least one of Cmd/Ctrl/Alt/Shift
    held down. Function keys, arrows, etc. aren't mapped in this first pass.
    """

    def __init__(self, initial_hotkey, parent=None):
        super().__init__(parent)
        self.hotkey = initial_hotkey
        self.setReadOnly(True)
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setPlaceholderText("Click, then press a combo…")
        self.setText(self._display(initial_hotkey))

    @staticmethod
    def _display(hotkey):
        return hotkey.replace("<", "").replace(">", "").replace("+", " + ").title()

    def keyPressEvent(self, event):
        key = event.key()
        if key in (Qt.Key.Key_Control, Qt.Key.Key_Shift, Qt.Key.Key_Alt, Qt.Key.Key_Meta):
            return  # wait for the actual (non-modifier) key

        mods = event.modifiers()
        parts = []
        if mods & Qt.KeyboardModifier.MetaModifier:
            parts.append("<cmd>")
        if mods & Qt.KeyboardModifier.ControlModifier:
            parts.append("<ctrl>")
        if mods & Qt.KeyboardModifier.AltModifier:
            parts.append("<alt>")
        if mods & Qt.KeyboardModifier.ShiftModifier:
            parts.append("<shift>")

        text = event.text()
        if not parts or not text or not text.isprintable():
            return  # require at least one modifier plus a real character

        parts.append(text.lower())
        self.hotkey = "+".join(parts)
        self.setText(self._display(self.hotkey))


class SettingsDialog(QDialog):
    """Minimal settings panel: global hotkey, auto-paste, link previews."""

    def __init__(self, current_hotkey, auto_paste, fetch_previews, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Clippy Settings")
        self.setFixedWidth(300)
        self.setStyleSheet("""
            QDialog { background-color: #1e1e1e; }
            QLabel { color: #cccccc; font-size: 12px; }
            QCheckBox { color: #cccccc; font-size: 12px; }
            QLineEdit {
                background-color: #2d2d2d; color: #ffffff; border: 1px solid #3c3c3c;
                border-radius: 6px; padding: 6px 10px; font-size: 13px;
            }
            QPushButton {
                background-color: #2d2d2d; color: #ffffff; border: 1px solid #3c3c3c;
                border-radius: 6px; padding: 6px 12px; font-size: 12px;
            }
            QPushButton:hover { background-color: #383838; }
        """)

        layout = QVBoxLayout(self)
        form = QFormLayout()
        form.setLabelAlignment(Qt.AlignmentFlag.AlignRight)

        self.hotkey_field = HotkeyCaptureField(current_hotkey, self)
        form.addRow("Global hotkey:", self.hotkey_field)

        self.auto_paste_checkbox = QCheckBox("Auto-paste (Cmd+V) after selecting", self)
        self.auto_paste_checkbox.setChecked(auto_paste)
        form.addRow(self.auto_paste_checkbox)

        self.fetch_previews_checkbox = QCheckBox("Fetch link title && favicon (uses network)", self)
        self.fetch_previews_checkbox.setChecked(fetch_previews)
        form.addRow(self.fetch_previews_checkbox)

        layout.addLayout(form)

        buttons = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel, self
        )
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        layout.addWidget(buttons)

    def result_values(self):
        return (
            self.hotkey_field.hotkey,
            self.auto_paste_checkbox.isChecked(),
            self.fetch_previews_checkbox.isChecked(),
        )


class ClipboardApp(QWidget):
    """Main application window for managing clipboard history."""

    MAX_HISTORY = 100

    def __init__(self):
        super().__init__()

        self.history = []
        self._content_index = {}   # dedup lookup: content-key -> item dict
        self._row_widgets = {}     # id(item) -> currently rendered row widget
        self.last_clip_text = ""
        self.last_image_key = None
        self.drag_position = QPoint()
        self.active_filter = "all"  # "all" | "text" | "image"

        self.hotkey = SETTINGS.value("hotkey", DEFAULT_HOTKEY, type=str)
        self.auto_paste_enabled = SETTINGS.value("auto_paste", True, type=bool)
        self.fetch_previews_enabled = SETTINGS.value("fetch_link_previews", False, type=bool)

        # UI widget declarations
        self.search_bar = None
        self.clear_btn = None
        self.settings_btn = None
        self.close_btn = None
        self.filter_all_btn = None
        self.filter_text_btn = None
        self.filter_image_btn = None
        self.list_widget = None
        self.toast_label = None

        # Native Qt clipboard instance
        self.clipboard = QApplication.clipboard()
        self.network_manager = QNetworkAccessManager(self)

        # Restore items pinned in a previous session, before the window (and
        # its list) is built.
        self._load_pinned()

        self.init_ui()

        # React to clipboard changes via Qt's own signal instead of constant
        # polling - near-instant detection with virtually no idle CPU cost.
        self.clipboard.dataChanged.connect(self.check_clipboard)

        # Kept as a low-frequency safety net in case a particular source
        # doesn't reliably emit dataChanged.
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.check_clipboard)
        self.timer.start(3000)

        # Timer for hiding toast notifications
        self.toast_timer = QTimer(self)
        self.toast_timer.setSingleShot(True)
        self.toast_timer.timeout.connect(self.hide_toast)

        # Global hotkey listener
        self.hotkey_signal = HotkeySignal()
        self.hotkey_signal.triggered.connect(self.toggle_window)
        self.listener_thread = HotkeyListenerThread(self.hotkey_signal, self.hotkey)
        self.listener_thread.start()

    def init_ui(self):
        """Build and style the application interface."""
        self.setWindowTitle("Clippy")

        window_flags = (
                Qt.WindowType.Window
                | Qt.WindowType.FramelessWindowHint
                | Qt.WindowType.WindowStaysOnTopHint
        )
        self.setWindowFlags(window_flags)
        self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground)
        self.resize(350, 520)

        # Dark theme styling matching dark grey popup UI
        self.setStyleSheet("""
            QWidget#MainFrame { 
                background-color: #1e1e1e; 
                border-radius: 12px; 
                border: 1px solid #333333; 
            }
            QLineEdit { 
                background-color: #2d2d2d; 
                color: #ffffff; 
                border: 1px solid #3c3c3c; 
                border-radius: 6px; 
                padding: 6px 10px; 
                font-size: 13px; 
            }
            QLineEdit:focus { border: 1px solid #007acc; }
            QPushButton { 
                background-color: #2d2d2d; 
                color: #aaaaaa; 
                border: 1px solid #3c3c3c; 
                border-radius: 6px; 
                padding: 6px 12px; 
                font-size: 12px; 
            }
            QPushButton:hover { background-color: #383838; color: #ffffff; }
            QPushButton:checked {
                background-color: #007acc;
                color: #ffffff;
                border: 1px solid #007acc;
            }
            QPushButton#IconBtn {
                background-color: transparent;
                color: #888888;
                border: none;
                font-size: 14px;
                padding: 2px 8px;
            }
            QPushButton#IconBtn:hover {
                color: #ffffff;
                background-color: #2d2d2d;
            }
            QPushButton#CloseBtn {
                background-color: transparent;
                color: #888888;
                border: none;
                font-size: 16px;
                font-weight: bold;
                padding: 2px 6px;
            }
            QPushButton#CloseBtn:hover {
                color: #ff5555;
                background-color: #2d2d2d;
            }
            QListWidget { 
                background-color: #252526; 
                color: #cccccc; 
                border: 1px solid #333333; 
                border-radius: 6px; 
                outline: none; 
            }
            QListWidget::item { 
                padding: 0px; 
                border-bottom: 1px solid #2d2d2d; 
                border-radius: 4px; 
            }
            QListWidget::item:hover { 
                background-color: #2a2d2e; 
            }
        """)

        main_layout = QVBoxLayout(self)
        main_layout.setContentsMargins(0, 0, 0, 0)

        container = QWidget(self)
        container.setObjectName("MainFrame")
        container_layout = QVBoxLayout(container)
        container_layout.setContentsMargins(18, 18, 18, 18)

        # Top control bar
        top_layout = QHBoxLayout()
        self.search_bar = QLineEdit(self)
        self.search_bar.setPlaceholderText("Search...")
        self.search_bar.textChanged.connect(lambda _text: self._render_list())
        top_layout.addWidget(self.search_bar)

        self.settings_btn = QPushButton("\u2699", self)  # gear
        self.settings_btn.setObjectName("IconBtn")
        self.settings_btn.setCursor(Qt.CursorShape.PointingHandCursor)
        self.settings_btn.setToolTip("Settings")
        self.settings_btn.clicked.connect(self.open_settings)
        top_layout.addWidget(self.settings_btn)

        self.clear_btn = QPushButton("Clear", self)
        self.clear_btn.setCursor(Qt.CursorShape.PointingHandCursor)
        self.clear_btn.clicked.connect(self.clear_history)
        top_layout.addWidget(self.clear_btn)

        # Close button to terminate the application
        self.close_btn = QPushButton("\u2715", self)
        self.close_btn.setObjectName("CloseBtn")
        self.close_btn.setCursor(Qt.CursorShape.PointingHandCursor)
        self.close_btn.setToolTip("Quit Clippy")
        self.close_btn.clicked.connect(QApplication.quit)
        top_layout.addWidget(self.close_btn)

        container_layout.addLayout(top_layout)

        # Quick type filter row
        filter_layout = QHBoxLayout()
        self.filter_all_btn = QPushButton("All", self)
        self.filter_text_btn = QPushButton("Text", self)
        self.filter_image_btn = QPushButton("Images", self)

        self.filter_group = QButtonGroup(self)
        self.filter_group.setExclusive(True)
        for btn, kind in (
            (self.filter_all_btn, "all"),
            (self.filter_text_btn, "text"),
            (self.filter_image_btn, "image"),
        ):
            btn.setCheckable(True)
            btn.setCursor(Qt.CursorShape.PointingHandCursor)
            btn.clicked.connect(lambda _checked, k=kind: self.set_filter(k))
            self.filter_group.addButton(btn)
            filter_layout.addWidget(btn)
        self.filter_all_btn.setChecked(True)

        container_layout.addLayout(filter_layout)

        # History list widget
        self.list_widget = QListWidget(self)
        self.list_widget.setVerticalScrollMode(
            QAbstractItemView.ScrollMode.ScrollPerPixel
        )
        self.list_widget.verticalScrollBar().setSingleStep(8)
        self.list_widget.setHorizontalScrollBarPolicy(
            Qt.ScrollBarPolicy.ScrollBarAlwaysOff
        )

        container_layout.addWidget(self.list_widget)
        main_layout.addWidget(container)
        self.setLayout(main_layout)

        # Small dark toast overlay next to cursor
        self.toast_label = QLabel("copied!", self)
        self.toast_label.setWindowFlags(
            Qt.WindowType.ToolTip | Qt.WindowType.FramelessWindowHint | Qt.WindowType.WindowStaysOnTopHint
        )
        self.toast_label.setStyleSheet("""
            QLabel {
                background-color: #2d2d2d;
                color: #cccccc;
                border: 1px solid #3c3c3c;
                border-radius: 5px;
                padding: 4px 8px;
                font-size: 11px;
            }
        """)
        self.toast_label.hide()

        self._render_list()

    def show_toast(self, message="copied!"):
        """Show a small dark popup right next to the mouse cursor."""
        self.toast_label.setText(message)
        self.toast_label.adjustSize()

        cursor_pos = QCursor.pos()
        self.toast_label.move(cursor_pos.x() + 15, cursor_pos.y() + 15)
        self.toast_label.show()

        self.toast_timer.start(1000)

    def hide_toast(self):
        """Hide the mouse overlay popup."""
        self.toast_label.hide()

    def mousePressEvent(self, event):
        """Capture mouse position for window dragging."""
        if event.button() == Qt.MouseButton.LeftButton:
            self.drag_position = (
                    event.globalPosition().toPoint() - self.frameGeometry().topLeft()
            )
            event.accept()

    def mouseMoveEvent(self, event):
        """Drag window framelessly across the screen."""
        if event.buttons() == Qt.MouseButton.LeftButton:
            self.move(event.globalPosition().toPoint() - self.drag_position)
            event.accept()

    # --- Settings / hotkey ------------------------------------------------

    def open_settings(self):
        dialog = SettingsDialog(self.hotkey, self.auto_paste_enabled, self.fetch_previews_enabled, self)
        if dialog.exec() == QDialog.DialogCode.Accepted:
            new_hotkey, auto_paste, fetch_previews = dialog.result_values()
            if new_hotkey != self.hotkey:
                self.apply_hotkey(new_hotkey)
            self.auto_paste_enabled = auto_paste
            SETTINGS.setValue("auto_paste", auto_paste)
            self.fetch_previews_enabled = fetch_previews
            SETTINGS.setValue("fetch_link_previews", fetch_previews)

    def apply_hotkey(self, hotkey):
        """Swap the running listener thread for one bound to the new combo."""
        self.hotkey = hotkey
        SETTINGS.setValue("hotkey", hotkey)
        if self.listener_thread:
            self.listener_thread.stop()
        self.listener_thread = HotkeyListenerThread(self.hotkey_signal, hotkey)
        self.listener_thread.start()

    # --- Persistence of pinned items ---------------------------------------

    @staticmethod
    def _make_image_key(image: QImage):
        """Cheap fingerprint used to recognize a previously-seen image."""
        img_bytes = image.bits().tobytes()
        return (image.width(), image.height(), len(img_bytes), hash(img_bytes[:1000]))

    @staticmethod
    def _content_key(item):
        """Stable key used for O(1) duplicate lookups."""
        if item["type"] == "text":
            return ("text", item["data"])
        if "path" in item:
            return ("image_path", item["path"])
        return ("image_key", item.get("key"))

    def _add_to_history(self, item, index=0):
        self.history.insert(index, item)
        self._content_index[self._content_key(item)] = item

    def _remove_from_history(self, item):
        """Remove one item from history + dedup index (list only, no widgets)."""
        try:
            self.history.remove(item)
        except ValueError:
            pass
        key = self._content_key(item)
        if self._content_index.get(key) is item:
            del self._content_index[key]

    @staticmethod
    def _serialize_item(item):
        """Turn a history entry into a JSON-safe dict for persisting pins."""
        if item["type"] == "text":
            payload = {"type": "text", "data": item["data"], "html": item.get("html", "")}
            if item.get("link_title"):
                payload["link_title"] = item["link_title"]
            if item.get("link_favicon_b64"):
                payload["link_favicon_b64"] = item["link_favicon_b64"]
            return payload

        image: QImage = item["data"]
        buffer = QBuffer()
        buffer.open(QIODevice.OpenModeFlag.WriteOnly)
        image.save(buffer, "PNG")
        image_b64 = base64.b64encode(bytes(buffer.data())).decode("ascii")
        buffer.close()
        return {"type": "image", "image_b64": image_b64, "path": item.get("path")}

    def _deserialize_item(self, raw):
        """Rebuild a history entry from a previously persisted dict, or None."""
        if raw.get("type") == "text":
            text = raw.get("data", "")
            item = {
                "type": "text",
                "data": text,
                "html": raw.get("html", ""),
                "pinned": True,
                "kind": classify_text(text),
            }
            if raw.get("link_title"):
                item["link_title"] = raw["link_title"]
                item["link_fetched"] = True
            if raw.get("link_favicon_b64"):
                item["link_favicon_b64"] = raw["link_favicon_b64"]
            return item

        if raw.get("type") == "image":
            try:
                png_bytes = base64.b64decode(raw.get("image_b64", ""))
            except (ValueError, TypeError):
                return None

            image = QImage()
            if not image.loadFromData(QByteArray(png_bytes), "PNG"):
                return None

            item = {"type": "image", "data": image, "pinned": True}
            saved_path = raw.get("path")
            if saved_path and os.path.isfile(saved_path):
                item["path"] = saved_path
            else:
                item["key"] = self._make_image_key(image)
            return item

        return None

    def _save_pinned(self):
        """Write every currently-pinned item to disk so a full quit doesn't lose them."""
        try:
            os.makedirs(APP_SUPPORT_DIR, exist_ok=True)
            payload = [self._serialize_item(it) for it in self.history if it.get("pinned")]
            tmp_path = PINNED_STORE_PATH + ".tmp"
            with open(tmp_path, "w", encoding="utf-8") as f:
                json.dump(payload, f)
            os.replace(tmp_path, PINNED_STORE_PATH)
        except OSError as e:
            print(f"[WARN] failed to save pinned items: {e}")

    def _load_pinned(self):
        """Load items pinned in a previous session, most-recently-pinned first."""
        if not os.path.isfile(PINNED_STORE_PATH):
            return

        try:
            with open(PINNED_STORE_PATH, "r", encoding="utf-8") as f:
                payload = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            print(f"[WARN] failed to load pinned items: {e}")
            return

        restored = [item for item in (self._deserialize_item(raw) for raw in payload) if item]
        self.history = restored + self.history
        for item in restored:
            self._content_index[self._content_key(item)] = item

    def _enforce_history_limit(self):
        """Trim oldest UNPINNED entries once history exceeds MAX_HISTORY."""
        while len(self.history) > self.MAX_HISTORY:
            idx = next(
                (i for i in range(len(self.history) - 1, -1, -1) if not self.history[i].get("pinned")),
                None,
            )
            if idx is None:
                break  # everything left is pinned; stop trimming
            self._remove_from_history(self.history[idx])

    # --- Link preview fetching (opt-in, off by default) ---------------------

    def _maybe_fetch_link_preview(self, item):
        if not self.fetch_previews_enabled or item.get("link_fetched"):
            return
        item["link_fetched"] = True

        raw = item["data"].strip()
        url = QUrl(raw if "://" in raw else "http://" + raw)
        if not url.host():
            return

        favicon_url = QUrl(f"https://www.google.com/s2/favicons?sz=64&domain={url.host()}")
        self._start_preview_request(favicon_url, item, "favicon")
        self._start_preview_request(url, item, "title")

    def _start_preview_request(self, url, item, kind):
        reply = self.network_manager.get(QNetworkRequest(url))
        reply.finished.connect(lambda: self._on_preview_reply(reply, item, kind))

    def _on_preview_reply(self, reply, item, kind):
        try:
            if reply.error() == reply.NetworkError.NoError:
                data = bytes(reply.readAll())
                if kind == "favicon" and data:
                    item["link_favicon_b64"] = base64.b64encode(data).decode("ascii")
                elif kind == "title":
                    match = TITLE_TAG_RE.search(data)
                    if match:
                        title = re.sub(r"\s+", " ", match.group(1).decode("utf-8", "ignore")).strip()
                        if title:
                            item["link_title"] = html.unescape(title)[:200]
                if item.get("pinned"):
                    self._save_pinned()
                self._refresh_row(item)
        finally:
            reply.deleteLater()

    def _refresh_row(self, item):
        row = self._row_widgets.get(id(item))
        if row is not None:
            row._build_content(item)

    # --- Clipboard polling / recording --------------------------------------

    def check_clipboard(self):
        """Poll the clipboard to detect new text, rich text (HTML), or images."""
        mime_data = self.clipboard.mimeData()
        if mime_data is None:
            return

        # Respect apps (e.g. password managers) that mark a copy as private.
        if any(mime_data.hasFormat(t) for t in PRIVATE_MARKER_TYPES):
            return

        # 1. Handle copied image files from Desktop or Finder
        if mime_data.hasUrls():
            urls = mime_data.urls()
            if urls and urls[0].isLocalFile():
                file_path = urls[0].toLocalFile()
                if file_path.lower().endswith(('.png', '.jpg', '.jpeg', '.webp', '.bmp', '.gif')):
                    if file_path != self.last_image_key:
                        image = QImage(file_path)
                        if not image.isNull():
                            self.last_image_key = file_path
                            self.last_clip_text = ""

                            key = ("image_path", file_path)
                            existing = self._content_index.get(key)
                            was_pinned = bool(existing and existing.get("pinned"))
                            if existing is not None:
                                self._remove_from_history(existing)

                            new_item = {"type": "image", "data": image, "path": file_path, "pinned": was_pinned}
                            self._add_to_history(new_item)
                            self._enforce_history_limit()
                            if was_pinned:
                                self._save_pinned()

                            self._render_list()
                    return

        # 2. Handle screenshots from memory
        if mime_data.hasImage():
            image: QImage = self.clipboard.image()
            if not image.isNull():
                img_key = self._make_image_key(image)

                if img_key != self.last_image_key:
                    self.last_image_key = img_key
                    self.last_clip_text = ""

                    key = ("image_key", img_key)
                    existing = self._content_index.get(key)
                    was_pinned = bool(existing and existing.get("pinned"))
                    if existing is not None:
                        self._remove_from_history(existing)

                    new_item = {"type": "image", "data": image, "key": img_key, "pinned": was_pinned}
                    self._add_to_history(new_item)
                    self._enforce_history_limit()
                    if was_pinned:
                        self._save_pinned()

                    self._render_list()

        # 3. Handle text with formatting (HTML + plain text fallback)
        elif mime_data.hasText():
            text = self.clipboard.text().strip()
            if not text:
                return

            html_text = mime_data.html() if mime_data.hasHtml() else ""

            if text != self.last_clip_text:
                self.last_clip_text = text
                self.last_image_key = None

                key = ("text", text)
                existing = self._content_index.get(key)
                was_pinned = bool(existing and existing.get("pinned"))
                if existing is not None:
                    self._remove_from_history(existing)

                kind = classify_text(text)
                new_item = {
                    "type": "text",
                    "data": text,
                    "html": html_text,
                    "pinned": was_pinned,
                    "kind": kind,
                }
                self._add_to_history(new_item)
                self._enforce_history_limit()
                if was_pinned:
                    self._save_pinned()
                if kind == "url":
                    self._maybe_fetch_link_preview(new_item)

                self._render_list()

    # --- List rendering ------------------------------------------------------

    def _sorted_history(self):
        """Pinned items first (in their existing relative order), then the rest."""
        return sorted(self.history, key=lambda it: 0 if it.get("pinned") else 1)

    def _add_item_to_widget(self, item):
        """Helper to create and insert a row (preview + pin/delete) into the list."""
        row = HistoryRowWidget(item)
        row.activated.connect(lambda it=item: self.paste_selected(it))
        row.pin_toggled.connect(lambda it=item: self.toggle_pin(it))
        row.delete_requested.connect(lambda it=item: self.delete_item(it))

        list_item = QListWidgetItem()
        list_item.setSizeHint(row.sizeHint())
        self.list_widget.addItem(list_item)
        self.list_widget.setItemWidget(list_item, row)

        self._row_widgets[id(item)] = row

    def _render_list(self):
        """Rebuild the visible list from history, applying the type filter and
        a simple "all words, any order" substring search."""
        query_words = self.search_bar.text().lower().split() if self.search_bar else []

        self.list_widget.clear()
        self._row_widgets.clear()

        for item in self._sorted_history():
            if self.active_filter == "text" and item["type"] != "text":
                continue
            if self.active_filter == "image" and item["type"] != "image":
                continue

            if query_words:
                if item["type"] != "text":
                    continue
                haystack = item["data"].lower()
                if not all(word in haystack for word in query_words):
                    continue

            self._add_item_to_widget(item)

    def set_filter(self, kind):
        self.active_filter = kind
        self._render_list()

    def toggle_pin(self, item):
        """Flip an entry's pinned state; pins are written to / removed from
        disk immediately, since only pinned items persist between launches."""
        item["pinned"] = not item.get("pinned", False)
        self._save_pinned()
        self._render_list()

    def delete_item(self, item):
        """Remove a single history entry (works for pinned entries too)."""
        was_pinned = item.get("pinned", False)
        self._remove_from_history(item)
        if was_pinned:
            self._save_pinned()
        self._render_list()

    def clear_history(self):
        """Wipe saved (unpinned) history and clear current clipboard.

        Pinned entries are intentionally kept - "Clear" is meant to sweep away
        clutter, not undo something the user deliberately pinned.
        """
        for item in [it for it in self.history if not it.get("pinned")]:
            self._remove_from_history(item)
        self.last_clip_text = ""
        self.last_image_key = None
        self.clipboard.clear()
        self._render_list()

    def paste_selected(self, item):
        """Copy the given history item back to the system clipboard, then
        optionally auto-paste it into whatever app had focus before Clippy."""
        if not item:
            return

        if item["type"] == "text":
            text = item["data"]
            html_text = item.get("html", "")
            self.last_clip_text = text
            self.last_image_key = None

            mime = QMimeData()
            mime.setText(text)
            if html_text:
                mime.setHtml(html_text)
            self.clipboard.setMimeData(mime)

        elif item["type"] == "image":
            image: QImage = item["data"]
            if "path" in item:
                self.last_image_key = item["path"]
                new_mime = QMimeData()
                new_mime.setUrls([QUrl.fromLocalFile(item["path"])])
                new_mime.setImageData(image)
                self.clipboard.setMimeData(new_mime)
            else:
                self.last_image_key = item.get("key")
                self.clipboard.setImage(image)
            self.last_clip_text = ""

        self.show_toast("copied!")

        if self.auto_paste_enabled and Quartz is not None and sys.platform == "darwin":
            self.hide()  # return focus to whatever app was active before Clippy
            QTimer.singleShot(80, simulate_cmd_v)

    def toggle_window(self):
        """Toggle window visibility strictly on shortcut call."""
        if self.isVisible():
            self.hide()
        else:
            self.search_bar.clear()
            self._render_list()
            self.show()
            self.raise_()
            self.activateWindow()
            self.search_bar.setFocus()

    def keyPressEvent(self, event):
        """Hide window on Escape key press."""
        if event.key() == Qt.Key.Key_Escape:
            self.hide()
        else:
            super().keyPressEvent(event)

    def shutdown(self):
        """Flush pinned items and stop the hotkey listener; safe to call twice."""
        self._save_pinned()
        if self.listener_thread:
            self.listener_thread.stop()

    def closeEvent(self, event):
        self.shutdown()
        event.accept()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    app.setQuitOnLastWindowClosed(False)

    window = ClipboardApp()
    app.aboutToQuit.connect(window.shutdown)

    sys.exit(app.exec())
